export type PropDocRow = {
  key: string;
  prop: string;
  type: string;
  required: string;
  description: string;
};

export const dataTablePropRows: PropDocRow[] = [
  {
    key: "tableId",
    prop: "tableId",
    type: "string",
    required: "yes",
    description:
      "Stable table id. Used for persisted column widths when columnResize is on.",
  },
  {
    key: "rowKey",
    prop: "rowKey",
    type: "TableProps['rowKey']",
    required: "yes",
    description: "Ant Design row key field name or getter.",
  },
  {
    key: "columnsInfo",
    prop: "columnsInfo",
    type: "DataTableColumnInfo<T>[]",
    required: "yes",
    description: "Column definitions (id, label, dataIndex, render, etc.).",
  },
  {
    key: "columnsInfo.sortable",
    prop: "columnsInfo[].sortable",
    type: "boolean",
    required: "no",
    description: "Enables click-to-sort on the column header.",
  },
  {
    key: "dataSource",
    prop: "dataSource",
    type: "T[]",
    required: "yes",
    description: "Row data. Rows must allow string index signature.",
  },
  {
    key: "pagination",
    prop: "pagination",
    type: "DataTablePaginationConfig",
    required: "yes",
    description:
      "pageSizeOptions and defaultPageSize; set totalItems when using serverMode for server paging.",
  },
  {
    key: "serverMode",
    prop: "serverMode",
    type: "boolean",
    required: "no",
    description:
      "Server mode toggle. true = page/search/filter are controlled outside the table; false/omitted = client mode.",
  },
  {
    key: "customColors",
    prop: "customColors",
    type: "DataTableCustomColors",
    required: "no",
    description:
      "Theme overrides for primary color plus lightMode/darkMode palette values (surface, border, text, row states).",
  },
  {
    key: "customColors.primaryColor",
    prop: "customColors.primaryColor",
    type: "string",
    required: "no",
    description:
      "Primary accent color used by interactive states (checkboxes, focus, selected icons, active bars).",
  },
  {
    key: "customColors.lightMode.popoverBg",
    prop: "customColors.lightMode.popoverBg",
    type: "string",
    required: "no",
    description:
      "Popover surface background in light mode (filters, column options, date presets).",
  },
  {
    key: "customColors.lightMode.popoverOptionHoverBg",
    prop: "customColors.lightMode.popoverOptionHoverBg",
    type: "string",
    required: "no",
    description: "Popover option hover background in light mode.",
  },
  {
    key: "customColors.lightMode.surfaceBg",
    prop: "customColors.lightMode.surfaceBg",
    type: "string",
    required: "no",
    description: "Main table surface background in light mode.",
  },
  {
    key: "customColors.lightMode.surfaceBorder",
    prop: "customColors.lightMode.surfaceBorder",
    type: "string",
    required: "no",
    description: "Table/panel border color in light mode.",
  },
  {
    key: "customColors.lightMode.textPrimary",
    prop: "customColors.lightMode.textPrimary",
    type: "string",
    required: "no",
    description: "Primary text color in light mode.",
  },
  {
    key: "customColors.lightMode.rowHoverBg",
    prop: "customColors.lightMode.rowHoverBg",
    type: "string",
    required: "no",
    description: "Row hover background in light mode.",
  },
  {
    key: "customColors.lightMode.rowSelectedBg",
    prop: "customColors.lightMode.rowSelectedBg",
    type: "string",
    required: "no",
    description: "Row selected background in light mode.",
  },
  {
    key: "customColors.lightMode.groupRowBg",
    prop: "customColors.lightMode.groupRowBg",
    type: "string",
    required: "no",
    description: "Group header row background in light mode.",
  },
  {
    key: "customColors.darkMode.popoverBg",
    prop: "customColors.darkMode.popoverBg",
    type: "string",
    required: "no",
    description:
      "Popover surface background in dark mode (filters, column options, date presets).",
  },
  {
    key: "customColors.darkMode.popoverOptionHoverBg",
    prop: "customColors.darkMode.popoverOptionHoverBg",
    type: "string",
    required: "no",
    description: "Popover option hover background in dark mode.",
  },
  {
    key: "customColors.darkMode.surfaceBg",
    prop: "customColors.darkMode.surfaceBg",
    type: "string",
    required: "no",
    description: "Main table surface background in dark mode.",
  },
  {
    key: "customColors.darkMode.surfaceBorder",
    prop: "customColors.darkMode.surfaceBorder",
    type: "string",
    required: "no",
    description: "Table/panel border color in dark mode.",
  },
  {
    key: "customColors.darkMode.textPrimary",
    prop: "customColors.darkMode.textPrimary",
    type: "string",
    required: "no",
    description: "Primary text color in dark mode.",
  },
  {
    key: "customColors.darkMode.rowHoverBg",
    prop: "customColors.darkMode.rowHoverBg",
    type: "string",
    required: "no",
    description: "Row hover background in dark mode.",
  },
  {
    key: "customColors.darkMode.rowSelectedBg",
    prop: "customColors.darkMode.rowSelectedBg",
    type: "string",
    required: "no",
    description: "Row selected background in dark mode.",
  },
  {
    key: "customColors.darkMode.groupRowBg",
    prop: "customColors.darkMode.groupRowBg",
    type: "string",
    required: "no",
    description: "Group header row background in dark mode.",
  },
  {
    key: "pagination.totalItems",
    prop: "pagination.totalItems",
    type: "number",
    required: "no",
    description:
      "Used with serverMode to compute footer totals and page count.",
  },
  {
    key: "className",
    prop: "className",
    type: "string",
    required: "no",
    description: "Extra class on the root wrapper.",
  },
  {
    key: "columnResize",
    prop: "columnResize",
    type: "boolean",
    required: "no",
    description: "Enable drag-to-resize columns; widths stored per tableId.",
  },
  {
    key: "filters",
    prop: "filters",
    type: "DataTableFilterConfig[]",
    required: "no",
    description:
      "Toolbar filter chips: date presets and/or multi-select options.",
  },
  {
    key: "filterValues",
    prop: "filterValues",
    type: "Record<string, unknown>",
    required: "no",
    description: "Controlled values for each filter id.",
  },
  {
    key: "onFilterChange",
    prop: "onFilterChange",
    type: "(filterId, value) => void",
    required: "no",
    description: "Update one filter when the user picks options or dates.",
  },
  {
    key: "groupConfig",
    prop: "groupConfig",
    type: "DataTableGroupConfig<T>",
    required: "no",
    description:
      "Groups rows by label; optional order and groupIcon. Client pagination counts data rows only and repeats group headers on each page as needed. The group title row spans all columns from the first visible column (put the label column first in columnsInfo).",
  },
  {
    key: "paginationState",
    prop: "paginationState",
    type: "{ page, pageSize }",
    required: "no",
    description: "Controlled page and page size.",
  },
  {
    key: "loading",
    prop: "loading",
    type: "boolean",
    required: "no",
    description: "Ant Design Table loading state.",
  },
  {
    key: "onRefresh",
    prop: "onRefresh",
    type: "() => void",
    required: "no",
    description: "Called when the refresh toolbar control is used.",
  },
  {
    key: "onFiltersChange",
    prop: "onFiltersChange",
    type: "(activeFilterIds: string[]) => void",
    required: "no",
    description: "Which filter chips are toggled on.",
  },
  {
    key: "onVisibleColumnsChange",
    prop: "onVisibleColumnsChange",
    type: "(visibleColumnIds: string[]) => void",
    required: "no",
    description: "Column visibility from the toggle-columns popover.",
  },
  {
    key: "onPageChange",
    prop: "onPageChange",
    type: "(page, pageSize) => void",
    required: "no",
    description: "Page or page size changed (toolbar pagination).",
  },
  {
    key: "sortState",
    prop: "sortState",
    type: "{ columnId: string; order: 'ascend' | 'descend' } | null",
    required: "no",
    description:
      "Controlled sorting state. Use with onSortChange, especially in serverMode.",
  },
  {
    key: "onSortChange",
    prop: "onSortChange",
    type: "(sortState) => void",
    required: "no",
    description:
      "Fires when column sorting changes. In client mode, sorting is handled internally by default; in serverMode, use this to fetch sorted data.",
  },
  {
    key: "renderToolbarRight",
    prop: "renderToolbarRight",
    type: "ReactNode",
    required: "no",
    description: "Right side of the filter toolbar (before column toggle).",
  },
  {
    key: "renderToolbarLeft",
    prop: "renderToolbarLeft",
    type: "ReactNode",
    required: "no",
    description: "Extra nodes after search on the left.",
  },
  {
    key: "searchValue",
    prop: "searchValue",
    type: "string",
    required: "no",
    description: "Controlled search field value.",
  },
  {
    key: "onSearch",
    prop: "onSearch",
    type: "(value: string) => void",
    required: "no",
    description: "Search input change. Omit both to hide search.",
  },
  {
    key: "searchPlaceholder",
    prop: "searchPlaceholder",
    type: "string",
    required: "no",
    description: "Placeholder for the search input.",
  },
  {
    key: "onSelectionChange",
    prop: "onSelectionChange",
    type: "(keys, rows) => void",
    required: "no",
    description: "Row selection changed.",
  },
  {
    key: "onBookmarkChange",
    prop: "onBookmarkChange",
    type: "(keys, rows) => void",
    required: "no",
    description: "Bookmarked rows changed.",
  },
  {
    key: "actions",
    prop: "actions",
    type: "DataTableActionsConfig<T>",
    required: "no",
    description:
      "Row actions menu, optional delete modal config, custom actions.",
  },
  {
    key: "disableSelectionAndBookmark",
    prop: "disableSelectionAndBookmark",
    type: "boolean",
    required: "no",
    description: "Hide selection column and bookmark controls.",
  },
  {
    key: "hideColumnOptions",
    prop: "hideColumnOptions",
    type: "boolean",
    required: "no",
    description: "Hide the toggle-visible-columns control.",
  },
  {
    key: "onRowClick",
    prop: "onRowClick",
    type: "(record: T) => void",
    required: "no",
    description: "Click handler on a data row.",
  },
  {
    key: "maxTableHeight",
    prop: "maxTableHeight",
    type: "string",
    required: "no",
    description: "CSS max-height for scrollable table body area.",
  },
];
